<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20231207084716 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE organisation_enhed_registrering DROP FOREIGN KEY FK_9770DD7EC42BE28C');
        $this->addSql('ALTER TABLE organisation_enhed_registrering DROP FOREIGN KEY FK_9770DD7E7B623DA6');
        $this->addSql('ALTER TABLE organisation_enhed_registrering_gyldighed DROP FOREIGN KEY FK_524E08625CBD4A93');
        $this->addSql('ALTER TABLE organisation_enhed_registrering_opgave DROP FOREIGN KEY FK_286AA33F5CBD4A93');
        $this->addSql('ALTER TABLE bruger_registrering_gyldighed DROP FOREIGN KEY FK_E6109CD9CB4DA18F');
        $this->addSql('ALTER TABLE organisation_funktion_registrering_gyldighed DROP FOREIGN KEY FK_5F9F042655A4FC6');
        $this->addSql('ALTER TABLE bruger_registrering_tilhoerer DROP FOREIGN KEY FK_B808BDE1CB4DA18F');
        $this->addSql('ALTER TABLE organisation_funktion_registrering_tilknyttede_organisationer DROP FOREIGN KEY FK_CF20252555A4FC6');
        $this->addSql('DROP TABLE organisation_enhed_registrering_gyldighed');
        $this->addSql('DROP TABLE organisation_enhed_registrering_opgave');
        $this->addSql('DROP TABLE bruger_registrering_gyldighed');
        $this->addSql('DROP TABLE organisation_funktion_registrering_gyldighed');
        $this->addSql('DROP TABLE bruger_registrering_tilhoerer');
        $this->addSql('DROP TABLE organisation_enhed_registrering_tilhoerer');
        $this->addSql('DROP TABLE organisation_funktion_registrering_tilknyttede_organisationer');
        $this->addSql('DROP TABLE organisation_enhed_registrering_enhedstype');
        $this->addSql('DROP INDEX UNIQ_9770DD7EC42BE28C ON organisation_enhed_registrering');
        $this->addSql('DROP INDEX UNIQ_9770DD7E7B623DA6 ON organisation_enhed_registrering');
        $this->addSql('ALTER TABLE organisation_enhed_registrering DROP enhedstype_id, DROP tilhoerer_id');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE organisation_enhed_registrering_gyldighed (id BINARY(16) NOT NULL COMMENT \'(DC2Type:uuid)\', organisation_enhed_registrering_id BINARY(16) NOT NULL COMMENT \'(DC2Type:uuid)\', virkning_fra_tidsstempel_dato_tid VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, virkning_fra_graense_indikator TINYINT(1) DEFAULT NULL, virkning_til_tidsstempel_dato_tid VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, virkning_til_graense_indikator TINYINT(1) DEFAULT NULL, virkning_aktoer_ref_uuididentifikator VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, virkning_aktoer_ref_urnidentifikator VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, virkning_aktoer_type_kode VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, virkning_note_tekst VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, gyldighed_status_kode VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, INDEX IDX_524E08625CBD4A93 (organisation_enhed_registrering_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE organisation_enhed_registrering_opgave (id BINARY(16) NOT NULL COMMENT \'(DC2Type:uuid)\', organisation_enhed_registrering_id BINARY(16) NOT NULL COMMENT \'(DC2Type:uuid)\', virkning_fra_tidsstempel_dato_tid VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, virkning_fra_graense_indikator TINYINT(1) DEFAULT NULL, virkning_til_tidsstempel_dato_tid VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, virkning_til_graense_indikator TINYINT(1) DEFAULT NULL, virkning_aktoer_ref_uuididentifikator VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, virkning_aktoer_ref_urnidentifikator VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, virkning_aktoer_type_kode VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, virkning_note_tekst VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, reference_id_uuididentifikator VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, reference_id_urnidentifikator VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, rolle_uuididentifikator VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, rolle_urnidentifikator VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, rolle_label VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, type_uuididentifikator VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, type_urnidentifikator VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, type_label VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, indeks VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, INDEX IDX_286AA33F5CBD4A93 (organisation_enhed_registrering_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE bruger_registrering_gyldighed (id BINARY(16) NOT NULL COMMENT \'(DC2Type:uuid)\', bruger_registrering_id BINARY(16) NOT NULL COMMENT \'(DC2Type:uuid)\', virkning_fra_tidsstempel_dato_tid VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, virkning_fra_graense_indikator TINYINT(1) DEFAULT NULL, virkning_til_tidsstempel_dato_tid VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, virkning_til_graense_indikator TINYINT(1) DEFAULT NULL, virkning_aktoer_ref_uuididentifikator VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, virkning_aktoer_ref_urnidentifikator VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, virkning_aktoer_type_kode VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, virkning_note_tekst VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, gyldighed_status_kode VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, INDEX IDX_E6109CD9CB4DA18F (bruger_registrering_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE organisation_funktion_registrering_gyldighed (id BINARY(16) NOT NULL COMMENT \'(DC2Type:uuid)\', organisation_funktion_registrering_id BINARY(16) NOT NULL COMMENT \'(DC2Type:uuid)\', virkning_fra_tidsstempel_dato_tid VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, virkning_fra_graense_indikator TINYINT(1) DEFAULT NULL, virkning_til_tidsstempel_dato_tid VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, virkning_til_graense_indikator TINYINT(1) DEFAULT NULL, virkning_aktoer_ref_uuididentifikator VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, virkning_aktoer_ref_urnidentifikator VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, virkning_aktoer_type_kode VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, virkning_note_tekst VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, gyldighed_status_kode VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, INDEX IDX_5F9F042655A4FC6 (organisation_funktion_registrering_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE bruger_registrering_tilhoerer (id BINARY(16) NOT NULL COMMENT \'(DC2Type:uuid)\', bruger_registrering_id BINARY(16) NOT NULL COMMENT \'(DC2Type:uuid)\', virkning_fra_tidsstempel_dato_tid VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, virkning_fra_graense_indikator TINYINT(1) DEFAULT NULL, virkning_til_tidsstempel_dato_tid VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, virkning_til_graense_indikator TINYINT(1) DEFAULT NULL, virkning_aktoer_ref_uuididentifikator VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, virkning_aktoer_ref_urnidentifikator VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, virkning_aktoer_type_kode VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, virkning_note_tekst VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, reference_id_uuididentifikator VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, reference_id_urnidentifikator VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, INDEX IDX_B808BDE1CB4DA18F (bruger_registrering_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE organisation_enhed_registrering_tilhoerer (id BINARY(16) NOT NULL COMMENT \'(DC2Type:uuid)\', virkning_fra_tidsstempel_dato_tid VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, virkning_fra_graense_indikator TINYINT(1) DEFAULT NULL, virkning_til_tidsstempel_dato_tid VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, virkning_til_graense_indikator TINYINT(1) DEFAULT NULL, virkning_aktoer_ref_uuididentifikator VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, virkning_aktoer_ref_urnidentifikator VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, virkning_aktoer_type_kode VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, virkning_note_tekst VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, reference_id_uuididentifikator VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, reference_id_urnidentifikator VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE organisation_funktion_registrering_tilknyttede_organisationer (id BINARY(16) NOT NULL COMMENT \'(DC2Type:uuid)\', organisation_funktion_registrering_id BINARY(16) NOT NULL COMMENT \'(DC2Type:uuid)\', virkning_fra_tidsstempel_dato_tid VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, virkning_fra_graense_indikator TINYINT(1) DEFAULT NULL, virkning_til_tidsstempel_dato_tid VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, virkning_til_graense_indikator TINYINT(1) DEFAULT NULL, virkning_aktoer_ref_uuididentifikator VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, virkning_aktoer_ref_urnidentifikator VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, virkning_aktoer_type_kode VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, virkning_note_tekst VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, reference_id_uuididentifikator VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, reference_id_urnidentifikator VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, INDEX IDX_CF20252555A4FC6 (organisation_funktion_registrering_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE organisation_enhed_registrering_enhedstype (id BINARY(16) NOT NULL COMMENT \'(DC2Type:uuid)\', virkning_fra_tidsstempel_dato_tid VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, virkning_fra_graense_indikator TINYINT(1) DEFAULT NULL, virkning_til_tidsstempel_dato_tid VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, virkning_til_graense_indikator TINYINT(1) DEFAULT NULL, virkning_aktoer_ref_uuididentifikator VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, virkning_aktoer_ref_urnidentifikator VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, virkning_aktoer_type_kode VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, virkning_note_tekst VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, reference_id_uuididentifikator VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, reference_id_urnidentifikator VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('ALTER TABLE organisation_enhed_registrering_gyldighed ADD CONSTRAINT FK_524E08625CBD4A93 FOREIGN KEY (organisation_enhed_registrering_id) REFERENCES organisation_enhed_registrering (id)');
        $this->addSql('ALTER TABLE organisation_enhed_registrering_opgave ADD CONSTRAINT FK_286AA33F5CBD4A93 FOREIGN KEY (organisation_enhed_registrering_id) REFERENCES organisation_enhed_registrering (id)');
        $this->addSql('ALTER TABLE bruger_registrering_gyldighed ADD CONSTRAINT FK_E6109CD9CB4DA18F FOREIGN KEY (bruger_registrering_id) REFERENCES bruger_registrering (id)');
        $this->addSql('ALTER TABLE organisation_funktion_registrering_gyldighed ADD CONSTRAINT FK_5F9F042655A4FC6 FOREIGN KEY (organisation_funktion_registrering_id) REFERENCES organisation_funktion_registrering (id)');
        $this->addSql('ALTER TABLE bruger_registrering_tilhoerer ADD CONSTRAINT FK_B808BDE1CB4DA18F FOREIGN KEY (bruger_registrering_id) REFERENCES bruger_registrering (id)');
        $this->addSql('ALTER TABLE organisation_funktion_registrering_tilknyttede_organisationer ADD CONSTRAINT FK_CF20252555A4FC6 FOREIGN KEY (organisation_funktion_registrering_id) REFERENCES organisation_funktion_registrering (id)');
        $this->addSql('ALTER TABLE organisation_enhed_registrering ADD enhedstype_id BINARY(16) DEFAULT NULL COMMENT \'(DC2Type:uuid)\', ADD tilhoerer_id BINARY(16) DEFAULT NULL COMMENT \'(DC2Type:uuid)\'');
        $this->addSql('ALTER TABLE organisation_enhed_registrering ADD CONSTRAINT FK_9770DD7E7B623DA6 FOREIGN KEY (enhedstype_id) REFERENCES organisation_enhed_registrering_enhedstype (id)');
        $this->addSql('ALTER TABLE organisation_enhed_registrering ADD CONSTRAINT FK_9770DD7EC42BE28C FOREIGN KEY (tilhoerer_id) REFERENCES organisation_enhed_registrering_tilhoerer (id)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_9770DD7EC42BE28C ON organisation_enhed_registrering (tilhoerer_id)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_9770DD7E7B623DA6 ON organisation_enhed_registrering (enhedstype_id)');
    }
}
